import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation,initPhysics} from '../src/simulation';import {CodeRuntime,makeHeadlessView} from '../src/code-runtime';import {prepareInvention} from '../src/spec';import {validateCode} from '../src/code-validation';
await initPhysics();
const rpg=prepareInvention(JSON.parse(fs.readFileSync('tests/fixtures/code/rpg.json','utf8')).invention);
test('Astra-authored RPG passes its observable behavior tests',async()=>{const result=await validateCode(rpg,0);assert.equal(result.ok,true,result.error);assert.ok(result.checks.length>=8);});
test('independent RPG test: travel, blast location, real physics breach and reload',()=>{
 const s=new Simulation();s.start(rpg);const view=makeHeadlessView();new CodeRuntime(s,view);s.aim={x:1,y:0,z:0};for(let i=0;i<3;i++)s.tick();
 const gate=s.entities.find(e=>e.id==='gate')!,left=s.entities.find(e=>e.id==='wall-left')!;const initialChildren=view.scene.children.length;
 s.activate();assert.equal(gate.removed,false);assert.ok(view.scene.children.length>=initialChildren);
 for(let i=0;i<4;i++)s.tick();assert.equal(gate.removed,false,'No instantaneous fake destruction');
 for(let i=0;i<45;i++)s.tick();assert.equal(gate.removed,true);assert.equal(gate.collider!.isValid(),false);assert.equal(left.removed,false);assert.equal(s.keyOwner,'guard','No key unlock substituted for an explosion');
 // Aim at the intact wall, rather than testing only one hardcoded target.
 s.player.setTranslation({x:-6,y:.85,z:-3.2},true);s.player.setLinvel({x:0,y:0,z:0},true);s.aim={x:1,y:0,z:0};for(let i=0;i<3;i++)s.tick();s.activate();for(let i=0;i<50;i++)s.tick();assert.equal(left.removed,true);assert.equal(s.entities.find(e=>e.id==='ground')!.removed,false);s.dispose();
});
for(const [name,level] of [['vine',1],['gravity',0]] as const)test(`Astra-authored ${name} implements new behavior and passes its tests`,async()=>{const spec=prepareInvention(JSON.parse(fs.readFileSync(`tests/fixtures/code/${name}.json`,'utf8')).invention);assert.equal(spec.phases.length,0,'No legacy action list');const result=await validateCode(spec,level);assert.equal(result.ok,true,result.error);assert.ok(result.checks.length>5);});
test('independent generated vine bridge carries the player over the gap',()=>{const spec=prepareInvention(JSON.parse(fs.readFileSync('tests/fixtures/code/vine.json','utf8')).invention);const s=new Simulation(1);s.start(spec);new CodeRuntime(s,makeHeadlessView());s.activate();for(let i=0;i<200;i++)s.tick();s.manual={x:3.2,y:0,z:0};for(let i=0;i<350&&s.state==='running';i++)s.tick();assert.equal(s.state,'won');assert.ok(s.position.y>.6);s.dispose();});
test('RPG built through the actual workbench fires, reloads and destroys physical walls',async()=>{const spec=prepareInvention(JSON.parse(fs.readFileSync('tests/fixtures/code/user-rpg.json','utf8')).invention);const result=await validateCode(spec,0);assert.equal(result.ok,true,result.error);assert.ok(result.checks.some(s=>s.includes('actual gate collider')));assert.ok(result.checks.some(s=>s.includes('Second rocket physically destroys')));});

test('low-thinking RPG passes authored checks and breaches a separately aimed wall',async()=>{const spec=prepareInvention(JSON.parse(fs.readFileSync('tests/fixtures/code/low-rpg.json','utf8')).invention);const result=await validateCode(spec,0);assert.equal(result.ok,true,result.error);const s=new Simulation();s.start(spec);new CodeRuntime(s,makeHeadlessView());s.player.setTranslation({x:-6,y:.85,z:-3.2},true);s.aim={x:1,y:0,z:0};for(let i=0;i<3;i++)s.tick();s.activate();for(let i=0;i<50;i++)s.tick();assert.equal(s.entities.find(e=>e.id==='wall-left')!.removed,true);assert.equal(s.entities.find(e=>e.id==='gate')!.removed,false);s.dispose();});

test('fast-first vine is rejected before equip and its medium repair supports an independent crossing',async()=>{const failed=prepareInvention(JSON.parse(fs.readFileSync('tests/fixtures/code/low-vine-failed.json','utf8')).invention);const rejection=await validateCode(failed,1);assert.equal(rejection.ok,false);assert.match(rejection.error||'',/physical support/);const fixed=prepareInvention(JSON.parse(fs.readFileSync('tests/fixtures/code/repaired-low-vine.json','utf8')).invention);const result=await validateCode(fixed,1);assert.equal(result.ok,true,result.error);const s=new Simulation(1);s.start(fixed);new CodeRuntime(s,makeHeadlessView());s.activate();for(let i=0;i<200;i++)s.tick();s.manual={x:3.2,y:0,z:0};for(let i=0;i<350&&s.state==='running';i++)s.tick();assert.equal(s.state,'won');assert.ok(s.position.y>.6);s.dispose();});
