import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation,initPhysics} from '../src/simulation.ts';import{prepareInvention}from'../src/spec.ts';
await initPhysics();
function item(op:string,extra:Record<string,unknown>={},mount='player',spawn=[0,0,0]){return prepareInvention({name:op,description:'Test mechanic',mount,spawn,parts:[{shape:'box',position:[0,0,0],rotation:[0,0,0],scale:[.2,.2,.2],color:'#aabbcc'}],phases:[{label:op,actions:[{op,target:'player',vector:[0,0,0],strength:0,radius:1,...extra}],until:{kind:op==='freezeRay'?'time':'never',target:'self',value:.12}}]});}
function settle(){const s=new Simulation();s.start(null);for(let i=0;i<20;i++)s.tick();return s;}
function aim(s:Simulation){const p=s.position,g=s.target('guard'),d={x:g.x-p.x,y:g.y-p.y-.86,z:g.z-p.z},len=Math.hypot(d.x,d.y,d.z);s.aim={x:d.x/len,y:d.y/len,z:d.z/len};}
test('ice ray requires aim, then can be fired again after missing',()=>{const s=settle();s.player.setTranslation({x:-1,y:.8,z:s.guard.z},true);s.equip(item('freezeRay',{target:'guard',strength:3,radius:5}));s.aim={x:-1,y:0,z:0};s.activate();for(let i=0;i<9;i++)s.tick();assert.equal(s.frozen,0);assert.ok(s.phaseDone);aim(s);s.activate();s.tick();assert.ok(s.frozen>0);assert.ok(s.beamHit);s.dispose();});
test('ice ray cannot freeze through the locked gate',()=>{const s=settle();s.player.setTranslation({x:5,y:.8,z:0},true);s.guard.z=0;s.distracted=2;s.equip(item('freezeRay',{target:'guard',strength:3,radius:5}));aim(s);s.activate();s.tick();assert.equal(s.frozen,0);assert.equal(s.beamHit,false);s.dispose();});
test('cloak hides the player without freezing the guard and permits a close pickpocket',()=>{const s=settle();s.equip(item('cloak'));s.activate();s.player.setTranslation({x:s.guard.x,y:.8,z:s.guard.z},true);s.tick();assert.ok(s.invisible);assert.equal(s.frozen,0);assert.equal(s.keyOwner,'player');assert.equal(s.alert,0);s.activate();s.tick();assert.equal(s.invisible,false);s.dispose();});
test('ladder requires proximity and forward movement, then climbs above the wall',()=>{const s=settle();s.equip(item('climb',{vector:[0,5.15,0],strength:2.8,radius:1.1},'free',[3.25,0,2.7]));s.activate();for(let i=0;i<60;i++)s.tick();assert.ok(s.position.y<.9);s.player.setTranslation({x:3.1,y:.8,z:2.7},true);for(let i=0;i<30;i++)s.tick();assert.ok(s.position.y<.9);s.manual={x:3.2,y:0,z:0};for(let i=0;i<180&&s.state==='running';i++)s.tick();assert.ok(s.maxHeight>4.8);assert.ok(s.position.x>4);s.dispose();});
test('trampoline waits for physical contact and then launches',()=>{const s=settle();s.equip(item('bounce',{vector:[4.5,10.5,0],radius:.9},'free',[2.5,.1,2.8]));s.activate();for(let i=0;i<30;i++)s.tick();assert.ok(s.position.y<.9);s.player.setTranslation({x:2.5,y:1.15,z:2.8},true);s.player.setLinvel({x:0,y:-1,z:0},true);s.tick();assert.ok(s.player.linvel().y>9);assert.ok(s.events.some(x=>x.startsWith('BOING')));s.dispose();});
test('teleport rejects a capsule landing inside a crate',()=>{const s=settle();s.equip(item('teleport',{vector:[-1,0,3]}));s.activate();s.tick();assert.ok(s.position.x< -5.9);assert.ok(Math.abs(s.position.z)<.1);assert.ok(s.events.some(x=>x.includes('No room')));s.dispose();});
test('stopping and restarting a timed invention resets its phase',()=>{const s=settle();s.equip(item('force',{vector:[0,1,0],strength:15}));s.activate();s.tick();assert.ok(s.inventionActive);s.activate();s.tick();assert.equal(s.inventionActive,false);s.activate();assert.equal(s.phase,0);assert.equal(s.phaseTime,0);s.dispose();});
