import fs from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';import {Simulation,initPhysics} from '../src/simulation';import {starters} from '../src/starters';
await initPhysics();
for(const level of [1,2] as const)test(`level ${level+1} cannot be solved by simply walking`,()=>{const s=new Simulation(level);s.start(null);s.manual={x:3.2,y:0,z:0};for(let i=0;i<600;i++)s.tick();assert.notEqual(s.state,'won');if(level===1)assert.equal(s.state,'lost');else assert.ok(s.position.x<3.5);s.dispose();});
test('blink crosses actual missing ground from the edge',()=>{const s=new Simulation(1);s.start(starters[1]);s.manual={x:3.2,y:0,z:0};for(let i=0;i<600&&s.state==='running';i++){if(s.position.x>-1.9&&!s.inventionActive)s.activate();s.tick();}assert.equal(s.state,'won',JSON.stringify(s.position));s.dispose();});
test('rooftop ladder gives height and a walkable rooftop exit',()=>{const s=new Simulation(2);s.start(starters[2]);s.activate();s.manual={x:3.2,y:0,z:0};for(let i=0;i<900&&s.state==='running';i++)s.tick();assert.equal(s.state,'won',JSON.stringify(s.position));assert.ok(s.maxHeight>4.8);s.dispose();});
test('retry begins with the same working invention and clean physics',()=>{let s=new Simulation(1);s.start(starters[1]);s.manual={x:3.2,y:0,z:0};for(let i=0;i<200;i++)s.tick();const spec=s.invention;s.dispose();s=new Simulation(1);s.start(spec);assert.equal(s.state,'running');assert.equal(s.position.x,-6);assert.equal(s.invention?.name,'Pocket Blink');assert.equal(s.inventionActive,false);s.dispose();});

for(const level of [1,2] as const)test(`fresh live-generated invention solves level ${level+1}`,()=>{const data=JSON.parse(fs.readFileSync(`tests/fixtures/playtest/level-${level}.json`,'utf8'));const s=new Simulation(level);s.start(data.invention);if(level===2)s.activate();let aligned=false;for(let i=0;i<1200&&s.state==='running';i++){if(level===2&&!aligned){const dz=s.self.z-s.position.z;aligned=Math.abs(dz)<.12;s.manual={x:0,y:0,z:Math.sign(dz)*3.2};}else s.manual={x:3.2,y:0,z:0};if(level===1&&s.position.x>-1.9&&!s.inventionActive)s.activate();s.tick();}assert.equal(s.state,'won',JSON.stringify(s.position));s.dispose();});
