import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation,initPhysics} from '../src/simulation.ts';
await initPhysics();
function settled(){const s=new Simulation();s.start(null);for(let i=0;i<30;i++)s.tick();return s;}
test('walking reaches speed within 100 ms and stops within 100 ms without sliding',()=>{const s=settled();s.manual={x:3.2,y:0,z:0};for(let i=0;i<6;i++)s.tick();assert.ok(s.player.linvel().x>3.15);const before=s.position.x;s.manual=null;for(let i=0;i<6;i++)s.tick();assert.ok(Math.abs(s.player.linvel().x)<.02);assert.ok(s.position.x-before<.15);s.dispose();});
test('forward and sideways movement have equal acceleration',()=>{const a=settled(),b=settled();a.manual={x:3.2,y:0,z:0};b.manual={x:0,y:0,z:3.2};for(let i=0;i<4;i++){a.tick();b.tick();}assert.ok(Math.abs(a.player.linvel().x-b.player.linvel().z)<.001);a.dispose();b.dispose();});
test('jump works on crates and cannot be repeated in midair',()=>{const s=settled();s.player.setTranslation({x:-7,y:1.63,z:3},true);s.player.setLinvel({x:0,y:0,z:0},true);for(let i=0;i<20;i++)s.tick();assert.ok(s.grounded);s.jump();s.tick();assert.ok(s.player.linvel().y>4);for(let i=0;i<12;i++)s.tick();const vy=s.player.linvel().y;s.jump();s.tick();assert.ok(s.player.linvel().y<vy);s.dispose();});
test('jump pressed just before landing is buffered',()=>{const s=settled();s.player.setTranslation({x:-6,y:.97,z:0},true);s.player.setLinvel({x:0,y:-3,z:0},true);s.jump();let jumped=false;for(let i=0;i<8;i++){s.tick();if(s.player.linvel().y>4)jumped=true;}assert.ok(jumped);s.dispose();});
test('walls block motion while allowing a slide along them',()=>{const s=settled();s.player.setTranslation({x:-8.5,y:.8,z:0},true);s.manual={x:-2.26,y:0,z:2.26};for(let i=0;i<50;i++)s.tick();assert.ok(s.position.x> -8.7);assert.ok(s.position.z>1);s.dispose();});
test('guard gives a recoverable warning before catching the player',()=>{const s=settled();s.player.setTranslation({x:s.guard.x,y:.8,z:s.guard.z},true);s.tick();assert.equal(s.state,'running');assert.ok(s.alert>0);s.player.setTranslation({x:-6,y:.8,z:0},true);for(let i=0;i<20;i++)s.tick();assert.equal(s.alert,0);assert.equal(s.state,'running');s.dispose();});
