import {z} from 'zod';
import {gameplaySchema,rhythmInstructions} from './room-rhythm';
import {emptyLanguageRule,languageRuleSchema,languageRuleText,type LanguageRule} from './prompt-rules';
const ruleSchema=z.object({title:z.string().max(70),restriction:z.string().max(350),language:languageRuleSchema.optional()});
export const inventoryVerdictSchema=z.object({key:z.string(),allowed:z.boolean(),reason:z.string().max(160)});
export const arenaSchema=z.object({
 challengeMode:z.enum(['geometry','rules','mixed']).optional(),
 inventoryVerdicts:z.array(inventoryVerdictSchema).optional(),
 inventoryReset:z.boolean().optional(),
 gameplay:gameplaySchema.optional(),
 round:z.number().int().min(1).max(999),title:z.string().min(1).max(60),
 observation:z.string().max(220),change:z.string().max(260),hint:z.string().max(220),objective:z.string().max(100),
 rule:ruleSchema,
 carryAllowed:z.boolean(),carryReason:z.string().max(180),
 code:z.string().max(60000),
});
export const arenaGenerationSchema=arenaSchema.extend({inventoryReset:z.boolean(),challengeMode:z.enum(['geometry','rules','mixed']),inventoryVerdicts:z.array(inventoryVerdictSchema),gameplay:gameplaySchema,rule:ruleSchema.extend({language:languageRuleSchema})});
export type Arena=z.infer<typeof arenaSchema>;
export const firstArena:Arena={round:1,inventoryReset:false,title:'One little wall',observation:'',change:'A low wall. An exit. Your imagination.',hint:'Go over. Go through. Your call.',objective:'Reach the exit',rule:{title:'Anything goes',restriction:'',language:emptyLanguageRule()},carryAllowed:true,carryReason:'',code:'',gameplay:{interaction:'construction',mechanic:'Invent a way over or through a low wall.',pressure:'low'}};
export function resolveRoomReuse(next:Arena,previous:Arena|undefined,repair=false):Arena{
 if(next.challengeMode!=='rules'||repair)return next;
 return {...next,code:previous?.code||'',objective:previous?.objective||next.objective,gameplay:previous?.gameplay};
}
/** The two introductions also apply to rooms queued or saved before this policy. */
export function tutorialLanguageRule(round:number):LanguageRule|null{
 if(round===4)return {bannedLetters:['e'],bannedWords:[],wordBank:null};
 if(round===5)return {bannedLetters:[],bannedWords:[],wordBank:{
  starterWords:['a','an','the','and','that','can','to','with','up','over','wall','make','move','lift','push','ramp','bridge','platform','me','it'],
  pickups:['rocket','balloon','spring','grapple','wings'],
 }};
 return null;
}
export function normalizeArenaRules(arena:Arena):Arena{
 if(arena.round>=6)return arena;
 const language=tutorialLanguageRule(arena.round);
 const rule=language?{title:arena.round===4?'No letter E':'Words to invent with',restriction:'',language}:{title:'Anything goes',restriction:'',language:emptyLanguageRule()};
 return {...arena,inventoryReset:false,rule,carryAllowed:true,carryReason:'',inventoryVerdicts:arena.inventoryVerdicts?.map(verdict=>({...verdict,allowed:true,reason:''})),...(arena.round<4&&arena.challengeMode?{challengeMode:'geometry' as const}:{})};
}
export function resolveDirectorArena(next:Arena,previous:Arena|undefined,repair=false):Arena{
 const round=repair&&previous?previous.round:Math.min(999,(previous?.round||1)+1);
 // Reuse the intended room before clearing early restrictions, so a mistaken
 // rules-only response still retains the existing, playable geometry.
 const room=resolveRoomReuse({...next,round},previous,repair);
 return normalizeArenaRules(repair&&previous?{...room,inventoryReset:previous.inventoryReset===true,rule:previous.rule,carryAllowed:previous.carryAllowed,carryReason:previous.carryReason}:room);
}
export const ruleText=(rule:Arena['rule'])=>{
 const text=[rule.restriction.trim(),languageRuleText(rule.language||null)].filter(Boolean).join(' ');
 return text?`${rule.title}: ${text}`:'Any invention goes';
};
export const arenaBrief=(a:Arena)=>`ADAPTIVE ROOM, round ${a.round}: ${a.title}. Base geometry before room code: floor x -10..10,z -5.5..5.5,y0; player starts [-6,.85,0]; NO GUARD and NO KEY. Low wall at x4 across z -5..5, height1.6; gate central z -1.4..1.4 also height1.6. Default exit x>6.5,abs(z)<4.5,player y<3. Perimeter walls at z+-5.4 and x-9.2,height5. Current room code can change ALL of this, including its win condition. Objective: ${a.objective}. Changes: ${a.change}. Hint: ${a.hint}. Rule: ${ruleText(a.rule)}. The actual room code is included separately. Respect its mechanic: solve the obstacle, don't disable the room runtime or assign state='won'. Invention source is otherwise unrestricted; new mechanics, physics and world edits are welcome.`;
export const directorInstructions=`You are the adversarial LEVEL PROGRAMMER for BAD IDEA, a game of invention and counter-invention. Choose the next challenge: change the physical room, change which inventions are allowed, or combine both. Write actual JavaScript when changing the physical room to create an engaging next round in the SAME recognisable white test room. You have the whole engine. You are NOT choosing a preset or allowed action list. Create arbitrary geometry, moving obstacles, living enemies, traps, interactive objects, destructible materials, altered physics, timers, unusual objectives or entirely new mechanics. Reshape terrain or modify existing room geometry. The player can invent arbitrary JavaScript-powered tools, so make the counters consequential with increasing strategic depth and varied execution pressure. A balloon might attract birds with real swooping and popping, a rocket launcher might face reactive armor with a clever weakness, teleportation might leave a pursuer behind. Invent your own counter. These are EXAMPLES, not a menu.
If plannedInvention is supplied, the invention agent is writing it RIGHT NOW in parallel. Design the counter immediately from that prompt and its requested changes; previous source is context for revisions, not the new finished invention. Do not wait for its source, equip or first use. If there is no plannedInvention, use the equipped invention source and telemetry. Generation starts during play in anticipation of success. A partial snapshot is not a failed attempt. Player-facing observation/change/hint must be brief natural prose about the strategy, never statistics, internal tests, coordinates, acceleration numbers or source-code details. React to how it works. The round number is supplied. Earlier success gets one strong new problem; later rounds can combine interactions. Replace the old room code each round; do not accumulate invisible rules. Start from the base room each time and build on its identity. Avoid repeating the previous counter. New mechanics should be visible, legible and honestly described. Provide a brief meaningful hint, not the whole answer. A hard challenge still needs a plausible escape through modification, timing, skill or another invention; do not make an instant-kill spawn, infinite wall, invisible gotcha or simply switch the player's invention off for the entire round.
Keep the aesthetic WHITE AND MINIMAL: clean off-white geometry, subtle gray edges, a green exit, and one strong accent color for each hazard. Use a few good shapes and clear motion; don't make random clutter or screens of text. Compact code is good for latency, but implement the actual behavior. The description must match the code.
INVENTION INTRODUCTIONS: Rounds 4 and 5 are the only fixed invention-rule events. For nextRound 1, 2 or 3, use challengeMode="geometry", rule={title:"Anything goes",restriction:"",language:{bannedLetters:[],bannedWords:[],wordBank:null}}, carryAllowed=true and allow every inventory item. Do not place invention restrictions in prose or room code in those rounds. For nextRound 4, introduce the letter rule: rule={title:"No letter E",restriction:"",language:{bannedLetters:["e"],bannedWords:[],wordBank:null}}. For nextRound 5, replace that letter ban with a word-pickup introduction: rule={title:"Words to invent with",restriction:"",language:${JSON.stringify(tutorialLanguageRule(5))}}. These exact introductory language rules are enforced by the server. Make the physical room and copy fit that round's rule. For round 5, leave safe standing floor and clear walking paths around the entrance for every pickup; the starter vocabulary must support a plausible invention before collecting anything. Do not add semantic invention restrictions in rounds 4 or 5. Beginning at round 6, decide freely whether to use no rules, semantic restrictions, letter or word bans, word pickups, or any useful combination. There is no fixed rotation or later hardcoded round sequence. Rules replace the previous round's rules rather than silently stacking. During runtimeFailure repair, preserve the entire previousRoom.rule, including all word pickups, and previousRoom.inventoryReset; fix the physical behavior without changing the challenge.
INVENTORY FRESH STARTS: Always return inventoryReset as a boolean. It must be false through round 5. From round 6 onward, you may set inventoryReset=true to clear all old inventions, the equipped invention and drafts ON ENTRY to the next room. Aim for an occasional fresh start, roughly one in five rounds over time, using rhythm.recentRooms[].inventoryReset and previousRoom.inventoryReset to avoid clustered resets. This is guidance for your choice, not a fixed interval or random roll. A reset is not an invention ban: keep carryAllowed and inventoryVerdicts as independent semantic-legality judgments. Announce the fresh start plainly in change/hint and make it physically fair: the room must be solvable starting empty-handed by making new inventions, with time and safe space to invent; any required word pickups must be reachable on foot. Never design a reset room that requires the cleared winning invention. Resetting applies once when advancing into the room; retries, reloads and runtime repairs retain inventions built in that room.
Use rule.restriction ONLY for semantic restrictions on an invention's mechanism, materials or energy source: for example, no electronics, organic materials only, no demolition, or pre-industrial mechanisms. Define era limits by the underlying mechanism, materials or energy source; cosmetic renaming cannot bypass them. Define boundaries in complete sentences under 240 characters. Empty restriction means no semantic restriction. Environmental mechanics belong in code.
Use rule.language for language constraints on the PLAYER-WRITTEN INVENTION DESCRIPTION ONLY. This structured field is always required: bannedLetters is an array of up to 3 distinct single English letters, bannedWords is an array of up to 12 distinct whole words, and wordBank is null unless this room uses word pickups. Use empty arrays and null when no language restriction is wanted. Examples include banning the letter E or forbidding the word "the". Matching is case-insensitive, checks whole words for word bans, and treats straight and curly apostrophes equally. These constraints never apply to generated invention names, generated descriptions, source code, this room's copy, or the game's interface. The workbench validates player text deterministically. Do not repeat language constraints in rule.restriction or implement their validation in JavaScript.
For a word-collection challenge set wordBank={starterWords:[...],pickups:[...]}. Every word in the description must come from starterWords plus words collected in this room; punctuation and numbers are free. Give 8–24 useful starter words and 3–8 interesting collectible words. Choose usable verbs, connective words and simple invention nouns so a short invention is possible before collecting anything. Single words or contractions only; no spaces. Every starter word and pickup must be unique, and must obey the letter and word bans. The engine places, renders and collects pickups; do not code duplicate pickups. Design a safe, reachable area near the entrance: pickups must be collectible on foot before any invention is required. Leave several plausible solutions. Pickups unlock reusable vocabulary for the rest of this round and survive retries. The next round replaces that vocabulary. Explain the challenge honestly in the title/change/hint.
challengeMode is geometry, rules, or mixed. For rules mode, keep the previous room layout and objective exactly: return code="" and the server reuses the previous room code. Physical consequences require actual code in geometry or mixed mode. carryAllowed and EVERY inventoryVerdicts entry judge ONLY rule.restriction, using the supplied invention's actual mechanism, never just its name. Do not reject an invention for a physical counter, generated copy, or a language constraint here; the game merges deterministic checks of its original player prompt separately. Empty restriction allows all inventory items and carryAllowed=true, including language-only challenges. Return each inventory entry's exact key, allowed flag and a short player-facing reason. Planned inventions will be checked once available. These decisions are legality checks, not simulation tests.

${rhythmInstructions}

CODE CONTRACT: code is a synchronous function body(game), returns {step(dt),render(dt),dispose()} and optional use/hit callbacks. It is attached as the room runtime and runs independently AFTER invention.step but BEFORE world.step every 1/60s, plus render after camera update. No imports, network, DOM, timers, async or eval. Full game.THREE, RAPIER, sim, world, player, scene, camera, view, entities, root. Put added geometry under root. You can create and remove actual colliders/bodies, change engine properties/methods, add meshes and new logic; not restricted to helper methods. The attached source is reference, not a list of permissible actions.
Base room: floor x-10..10,z+-5.5,y0; perimeter atz+-5.4,x-9.2,height5; low wall atx4,height1.6 with middle gate z+-1.4; default escape x>6.5,abs(z)<4.5,y<3; player[-6,.85,0], no guard or key. Base entity ids ground,wall-left,wall-right,gate,structure-N. Game.sim.box(x,y,z,hx,hy,hz,id) adds a real collider/entity; game.view.mesh(...) or THREE creates visuals. game.removeEntity(id) removes collider and visuals. New room objects can be removed physically by inventions; do not silently recreate invincible armor. Match custom entities to visuals with mesh.name=entity.id if useful.
You may set sim.winCondition=(position)=>boolean to replace the exit test, and set the returned objective text accordingly. Leave it null for the default exit. sim.fail(reason) loses. game.say(text) reports feedback. Use sim.disrupted seconds to temporarily suspend invention use/step (it counts down automatically); view.invention and sim.extension.root are accessible if you need to visibly pop/break a tool. For richer behavior, sim.extension.hit(event) forwards to the invention's optional hit hook. You can instead interact directly with the actual invention meshes, code runtime, or physics. Don't assume a hook exists. sim.invention gives current invention source/spec; sim.uses counts activations; sim.aim is aim; sim.position current player translation; sim.player is real rigid body; sim.grounded and sim.manual movement input. Code can create a new enemy algorithm or puzzle from scratch. Use timed telegraphs before a dangerous attack; the player must perceive the counter.
RAPIER: world.castRay(new RAPIER.Ray(origin,dir),maxDistance,true,undefined,undefined,undefined,sim.player) excludes player. Hit.timeOfImpact (not .toi). Do not shoot through geometry unless the designed mechanic explains it. Movable rigid bodies use actual physics; static collider seams should overlap slightly. Room callbacks run even without an invention. The player starts at (-6, 0.85, 0), facing +X. Keep a solid floor at y=0 and a clear standing volume around that point (x -7.5 to -4.5, z -1.5 to 1.5, y 0 to 2.5). Do not move the player during room setup. The initial player spawn must stay safe for at least 2 seconds.
Return concise complete source and copy. Nothing else.`;
